(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let speed=.42,runningAll=false,processed=0,qa=0,fixed=0,exported=0;
const capabilities=[
['docs','PDF → Excel / Word','doc',['SCAN','STRUCTURE','CONVERT','QA']],['docs','メモ → PowerPoint','doc',['PARSE','OUTLINE','LAYOUT','EXPORT']],['docs','一覧100件を入力','table',['MAP','TYPE','NORMALIZE','COUNT']],['docs','領収書 → Excel','table',['READ','EXTRACT','SORT','RECONCILE']],['docs','アンケート集計 + グラフ','chart',['VALIDATE','AGGREGATE','CROSS TAB','CHART']],['docs','PDFに入力欄を追加','doc',['DETECT','FIELD MAP','INJECT','TEST']],['docs','住所録・顧客リスト清掃','table',['PROFILE','DEDUP','FILL','SORT']],['docs','予定表 → CSV / ICS','table',['PARSE','TIMEZONE','SERIALIZE','COUNT']],
['shop','商品10件をショップ登録','shop',['IMAGE','COPY','OPTIONS','VERIFY']],['shop','フリマ10件を出品準備','shop',['PHOTO','TITLE','PRICE','PACK']],['shop','WordPress 5記事入稿','web',['STRUCTURE','MEDIA','LINKS','PREVIEW']],['shop','名刺・ショップカード','design',['GRID','QR','TYPE','PRINT QA']],['shop','メニュー・料金表','design',['GROUP','PRICE','PHOTO','EXPORT']],['shop','予約・申込フォーム','form',['QUESTIONS','FORM','SHEET','TEST']],['shop','イベント受付セット','form',['FORM','QR','ROSTER','GUIDE']],
['media','写真30枚 → 思い出ムービー','media',['SORT','TIMELINE','CAPTION','FHD']],['media','動画 → ショート3本','media',['DETECT','CUT','CAPTION','9:16']],['media','写真500枚を整理','media',['HASH','GROUP','DEDUP','INDEX']],['media','画像10枚をWeb最適化','media',['CROP','RESIZE','COMPRESS','QA']],['media','音声20分を聞きやすく','audio',['DENOISE','LEVEL','TRIM','EXPORT']],['media','動画10分を仕上げ','media',['CUT','AUDIO','COLOR','RENDER']],['media','会議音声 → 議事録','text',['TRANSCRIBE','SUMMARIZE','DECISIONS','TODO']],
['pc','フォルダ1000件を整理','files',['SCAN','CLASSIFY','DEDUP','MANIFEST']],['pc','事務作業60分を整理','files',['QUEUE','BATCH','VERIFY','RECEIPT']],['pc','PC不調を切り分け','code',['OBSERVE','ISOLATE','FIX','VERIFY']],['pc','Webページの不具合修正','web',['REPRO','PATCH','VIEWPORT QA','ROLLBACK']],
['research','候補10ソースを比較','research',['SEARCH','FILTER','COMPARE','CITE']],['research','文章8,000字を整える','text',['PARSE','REWRITE','SHORTEN','QA']],['research','告知文 + SNS + FAQ','text',['ANGLE','VARIANTS','FAQ','PACK']],['research','履歴書・職務経歴書整理','doc',['FACT LOCK','STRUCTURE','BULLETS','LAYOUT']],
['tech','自動化のバグ1個修正','code',['REPRO','TRACE','PATCH','REGRESSION']],['tech','サービス / APIを1個接続','route',['AUTH','MAP','CALL','VERIFY']],['tech','Agent / RAGの壊れ方を潰す','route',['FAULT','ROUTE','RECOVER','RECEIPT']]
];
const works=[
['SYSTEM','AgentLink','PC・スマホ・AI・外部サービスを長時間つなぐ基盤。','https://github.com/paper-daemon/AgentLink'],['PRODUCTION','AI Production Control Room','依頼整理 → 制作 → QA → 差分修正 → 納品。','/portfolio/ai-production-control-room.html'],['AUTOMATION','建設日報 自動化','CSV検証・集計から日本語日報まで。','/portfolio/construction-daily-report-automation.html'],['RAG','RAG Fleet Harness','routing / source / health / validation。','https://github.com/paper-daemon/AgentLink/blob/main/CASE_STUDY_RAG_FLEET.md'],['RECOVERY','Receipt Replay Simulator','skip / retry / reconcileを分離する実験。','https://github.com/paper-daemon/AgentLink/tree/main/demos/receipt-replay-simulator'],['NOTE','systemd --user debug','user serviceが死ぬ時の切り分け。','/notes/linux-user-service-debug.html'],['NOTE','Debuggable RAG','RAGが外した理由を追える構成。','/notes/debuggable-rag.html'],['NOTE','Image model benchmark','ローカル画像モデル比較記録。','/notes/image-model-benchmark.html'],['NOTE','Proof of Antiquity','古いデータを残す小さい実験。','/notes/proof-of-antiquity.html'],['TOOL','Delivery Inspector','動画・音声の納品前メタデータ確認。','/creator-delivery-inspector/'],['TOOL','Hosting Launch Checker','公開前サイトの静的チェック。','/hosting-launch-checker/'],['TOOL','AI Work Router','作業をAI / routeへ振り分ける判断器。','/ai-work-router/'],['TOOL','Creator Stack Picker','制作環境の選択を整理する道具。','/creator-stack-picker/']
];
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function updateStats(){setText('#dh-processed',processed);setText('#dh-qa',qa);setText('#dh-fixed',fixed);setText('#dh-exported',exported);setText('#dh-active',runningAll?'46':'0')}
function buildProofs(){const box=$('#dh-proof-grid');if(!box)return;box.innerHTML=works.map((w,i)=>`<a class="dh-proof" data-module="${i}" href="${w[3]}"><small>${String(i+1).padStart(2,'0')} / ${w[0]}</small><b>${w[1]}</b><p>${w[2]}</p></a>`).join('')}
const cats={docs:'01 / 書類・入力',shop:'02 / 売る・お店',media:'03 / 写真・動画・音',pc:'04 / 片付け・PC',research:'05 / 調べる・文章',tech:'06 / 開発・自動化'};
function buildCaps(){const box=$('#dh-cap-list');if(!box)return;box.innerHTML=Object.entries(cats).map(([k,label])=>`<section class="dh-cat"><h3>${label}</h3>${capabilities.map((c,i)=>c[0]===k?`<button class="dh-cap-btn" data-cap="${i}">${c[1]}</button>`:'').join('')}</section>`).join('');$$('.dh-cap-btn',box).forEach(b=>b.addEventListener('click',()=>runCapability(+b.dataset.cap,true)))}
function stageBase(title,type){const stage=$('#dh-cap-result');$('#dh-cap-title').textContent=title;$('#dh-cap-type').textContent=type.toUpperCase()+' / LOCAL MICRO DEMO';stage.innerHTML='';return stage}
function steps(labels){const box=$('#dh-cap-log');box.innerHTML=labels.map((x,i)=>`<div class="dh-cap-step" data-step="${i}"><small>0${i+1}</small><b>${x}</b></div>`).join('')}
async function flashSteps(labels){steps(labels);for(let i=0;i<labels.length;i++){await sleep(reduced?15:Math.max(40,115*speed));const e=$(`.dh-cap-step[data-step="${i}"]`);if(e)e.classList.add('on');qa++}}
function sheet(x,y,w=180,h=150,label='SOURCE'){const d=document.createElement('div');d.className='micro-sheet';d.style.cssText=`left:${x}%;top:${y}%;width:${w}px;height:${h}px`;d.innerHTML=`<h4>${label}</h4>${'<span></span>'.repeat(7)}`;return d}
function chip(stage,text,x,y,cls=''){const c=document.createElement('div');c.className='micro-chip '+cls;c.textContent=text;c.style.cssText=`left:${x}%;top:${y}%`;stage.appendChild(c);return c}
async function demoDoc(title,labels){const s=stageBase(title,'document');const a=sheet(7,18,170,190,'SOURCE');const b=sheet(66,18,170,190,'EDITABLE OUTPUT');b.style.opacity=.22;s.append(a,b);chip(s,'OCR / PARSE',42,28);chip(s,'STRUCTURE',43,45);chip(s,'QA',46,62,'good');await flashSteps(labels);b.style.opacity=1;b.style.transform='translateX(-8px)';a.style.transform='translateX(8px)';exported++}
async function demoTable(title,labels){const s=stageBase(title,'data table');for(let i=0;i<8;i++){const r=document.createElement('div');r.className='micro-row'+(i===2||i===5?' bad':'');r.style.top=`${9+i*10}%`;r.innerHTML=`<b>${1001+i}</b><span>${i===2?'09/03/26':'2026-09-03'}</span><span>${i===5?'NULL':(1200+i*340)}</span><span>${i===2||i===5?'CHECK':'OK'}</span>`;s.appendChild(r)}await flashSteps(labels);$$('.micro-row',s).forEach((r,i)=>setTimeout(()=>{r.classList.remove('bad');r.classList.add('good')},reduced?0:i*26));fixed+=2;exported++}
async function demoChart(title,labels){const s=stageBase(title,'aggregate');const wrap=document.createElement('div');wrap.className='dh-bars';for(let i=0;i<18;i++){const b=document.createElement('div');b.className='dh-bar';wrap.appendChild(b)}s.appendChild(wrap);await flashSteps(labels);$$('.dh-bar',s).forEach((b,i)=>{b.style.height=(22+((i*37)%70))+'%';b.classList.add(i%5===0?'bad':'good')});fixed+=4;exported++}
async function demoShop(title,labels){const s=stageBase(title,'commerce');for(let i=0;i<8;i++){const p=document.createElement('div');p.className='micro-photo';p.style.cssText=`left:${7+(i%4)*22}%;top:${12+Math.floor(i/4)*43}%;`;p.innerHTML=`<span style="position:absolute;left:6px;bottom:5px;font:800 7px monospace">SKU-${210+i}</span>`;s.appendChild(p)}await flashSteps(labels);$$('.micro-photo',s).forEach((p,i)=>setTimeout(()=>p.classList.add('good'),i*20));exported+=8}
async function demoMedia(title,labels,audio=false){const s=stageBase(title,audio?'audio':'media');const wave=document.createElement('div');wave.className='dh-bars';for(let i=0;i<32;i++){const b=document.createElement('div');b.className='dh-bar';b.style.height=(10+((i*53)%86))+'%';wave.appendChild(b)}s.appendChild(wave);await flashSteps(labels);$$('.dh-bar',s).forEach((b,i)=>{b.style.height=(22+((i*29)%65))+'%';b.classList.add(i%9===0?'bad':'good')});fixed+=3;exported++}
async function demoWeb(title,labels){const s=stageBase(title,'responsive web');const d=document.createElement('div');d.className='dh-devices';d.innerHTML='<div class="dh-device"></div><div class="dh-device"></div><div class="dh-device bad"></div>';s.appendChild(d);await flashSteps(labels);const bad=$('.dh-device.bad',s);bad.classList.remove('bad');bad.classList.add('good');$$('.dh-device',s).forEach(x=>x.classList.add('good'));fixed++;exported++}
async function demoText(title,labels){const s=stageBase(title,'text');const a=sheet(8,13,240,230,'RAW');const b=sheet(60,13,240,230,'DELIVERABLE');b.style.opacity=.2;s.append(a,b);await flashSteps(labels);b.style.opacity=1;chip(s,'FACTS LOCKED',42,72,'good');exported++}
async function demoFiles(title,labels){const s=stageBase(title,'filesystem');for(let i=0;i<22;i++)chip(s,`f_${String(i+1).padStart(3,'0')}`,6+(i%6)*15,8+Math.floor(i/6)*20,i%8===0?'bad':'');await flashSteps(labels);$$('.micro-chip.bad',s).forEach((c,i)=>setTimeout(()=>{c.classList.remove('bad');c.classList.add('good');c.style.left=(73+(i%2)*10)+'%'},i*40));fixed+=3;exported++}
async function demoResearch(title,labels){const s=stageBase(title,'research');for(let i=0;i<10;i++){const sh=sheet(4+(i%5)*19,9+Math.floor(i/5)*48,125,145,`SOURCE ${i+1}`);sh.style.transform=`rotate(${(i%3-1)*1.3}deg)`;s.appendChild(sh)}await flashSteps(labels);chip(s,'10 SOURCES',40,40,'good');chip(s,'COMPARE',44,57,'good');exported++}
async function demoCode(title,labels,route=false){const s=stageBase(title,route?'routing / agent':'debug / code');if(route){const pts=[[10,42,'INPUT'],[30,20,'ROUTER'],[30,67,'GUARD'],[56,18,'A'],[56,48,'B'],[56,75,'C'],[82,45,'OUTPUT']];pts.forEach(([x,y,t],i)=>{const n=document.createElement('div');n.className='dh-flow-node';n.style.cssText=`left:${x}%;top:${y}%`;n.innerHTML=`<small>NODE ${i+1}</small><b>${t}</b><i></i>`;s.appendChild(n)});await flashSteps(labels);$$('.dh-flow-node',s).forEach((n,i)=>setTimeout(()=>n.classList.add(i===4?'warn':'on'),i*35));setTimeout(()=>{$$('.dh-flow-node.warn',s).forEach(n=>{n.classList.remove('warn');n.classList.add('on')})},260);fixed++;exported++}else{const c=document.createElement('div');c.className='micro-code';c.innerHTML='10:14:22  reproduce issue...<br>10:14:22  <span class="bad">FAIL / unexpected null</span><br>10:14:23  trace → normalizePayload()<br>10:14:23  patch line 84<br>10:14:23  regression × 12<br><span class="ok">10:14:24  PASS / 12 of 12</span>';s.appendChild(c);await flashSteps(labels);fixed++;exported++}}
async function runCapability(i,user=false){if(i<0||i>=capabilities.length)return;$$('.dh-cap-btn').forEach(b=>b.classList.toggle('active',+b.dataset.cap===i));const c=capabilities[i],type=c[2];processed++;if(user)$('#dh-cap-stage').scrollIntoView({block:'nearest',behavior:'smooth'});if(type==='doc')await demoDoc(c[1],c[3]);else if(type==='table')await demoTable(c[1],c[3]);else if(type==='chart')await demoChart(c[1],c[3]);else if(type==='shop'||type==='design'||type==='form')await demoShop(c[1],c[3]);else if(type==='media')await demoMedia(c[1],c[3]);else if(type==='audio')await demoMedia(c[1],c[3],true);else if(type==='web')await demoWeb(c[1],c[3]);else if(type==='text')await demoText(c[1],c[3]);else if(type==='files')await demoFiles(c[1],c[3]);else if(type==='research')await demoResearch(c[1],c[3]);else if(type==='code')await demoCode(c[1],c[3]);else if(type==='route')await demoCode(c[1],c[3],true);updateStats()}
function pulseLanes(){const lanes=$$('.dh-lane');lanes.forEach((l,i)=>setTimeout(()=>{l.classList.remove('hot');void l.offsetWidth;l.style.setProperty('--dur',`${Math.max(.18,.56*speed)}s`);l.classList.add('hot')},i*35));setTimeout(()=>lanes.forEach(l=>l.classList.remove('hot')),700)}
function animateFlagships(){const flags=$$('.dh-flag');let tick=0;const run=()=>{if(document.hidden)return;tick++;flags.forEach((f,fi)=>{if(fi===0){$$('.dh-flow-node',f).forEach((n,i)=>n.classList.toggle('on',(i+tick)%4<2));}else if(fi===1){$$('.dh-cell',f).forEach((n,i)=>{n.classList.remove('on','bad');n.classList.add((i+tick)%7===0?'bad':'on')})}else if(fi===2){$$('.dh-bar',f).forEach((b,i)=>{b.style.height=(18+((i*31+tick*13)%75))+'%';b.className='dh-bar '+(((i+tick)%6===0)?'bad':'good')})}else if(fi===3){$$('.dh-device',f).forEach((d,i)=>{d.classList.remove('bad','good');d.classList.add((i===2&&tick%4===0)?'bad':'good')})}});pulseLanes()};run();return setInterval(run,reduced?3000:Math.max(480,1250*speed))}
async function runAll(){if(runningAll)return;runningAll=true;processed=qa=fixed=exported=0;updateStats();$('#dh-live').classList.add('running');$('#dh-live span').textContent='RUNNING ALL 46';const proofs=$$('.dh-proof');for(let i=0;i<proofs.length;i++){proofs[i].style.background='#e8f2e6';processed++;qa++;if(i%3===0)exported++;pulseLanes();updateStats();await sleep(reduced?8:Math.max(18,52*speed));proofs[i].style.background=''}for(let i=0;i<capabilities.length;i++){await runCapability(i,false);await sleep(reduced?8:Math.max(12,36*speed))}runningAll=false;$('#dh-live span').textContent='COMPLETE / 46 MODULES';setText('#dh-active','0');setTimeout(()=>{$('#dh-live').classList.remove('running');$('#dh-live span').textContent='READY / FAST LOCAL DEMOS'},1400)}
function initControls(){$('#dh-run-all')?.addEventListener('click',runAll);$('#dh-turbo')?.addEventListener('click',e=>{speed=.25;e.currentTarget.classList.add('active');$('#dh-normal')?.classList.remove('active')});$('#dh-normal')?.addEventListener('click',e=>{speed=.7;e.currentTarget.classList.add('active');$('#dh-turbo')?.classList.remove('active')})}
function initLazy(){let timer=null;const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!timer)timer=animateFlagships();else if(!e.isIntersecting&&timer){clearInterval(timer);timer=null}}),{rootMargin:'250px'});const target=$('#dh-flagships');if(target)io.observe(target)}
buildProofs();buildCaps();initControls();initLazy();updateStats();runCapability(0,false);
})();