(() => {
const navStyle=document.createElement('link');navStyle.rel='stylesheet';navStyle.href='/nav-icons.css';document.head.append(navStyle);
const samples={trace:`{"trace_id":"a1","event_id":"e1","step":"fetch","ms":120}\n{"trace_id":"a1","event_id":"e2","step":"transform","ms":860}\n{"trace_id":"a1","event_id":"e2","step":"transform","ms":860}\nnot-json`,srt:`1\n00:00:00,000 --> 00:00:02,400\n最初の字幕\n\n2\n00:00:02,200 --> 00:00:05,800\n少し重なる字幕\n\n3\n00:00:09,800 --> 00:00:13,000\n長い空白のあと`,retry:`{"attempts":4,"base_ms":400,"concurrency":6,"success_rate":0.68}`,csv:` name , email , status\n Alice ,alice@example.com, ok\nBob,bob@example.com, pending\n Alice ,alice@example.com, ok\nCharlie, , ok`};
const input=document.querySelector('#lab-input'),output=document.querySelector('#lab-output'),run=document.querySelector('#lab-run'),tabs=[...document.querySelectorAll('[data-mode]')];if(!input||!output)return;let mode='trace';
const parseTime=s=>{const m=s.match(/(\d\d):(\d\d):(\d\d),(\d\d\d)/);return m?(((+m[1]*60 + +m[2])*60 + +m[3])*1000 + +m[4]):NaN};
function trace(text){const seen=new Set(),traces={},issues=[];text.split(/\n+/).filter(Boolean).forEach((line,i)=>{try{const r=JSON.parse(line),id=r.event_id||`line-${i+1}`,k=r.trace_id||'unknown';if(seen.has(id))issues.push(`duplicate event_id: ${id}`);seen.add(id);traces[k]??={events:0,total_ms:0,max_ms:0};traces[k].events++;traces[k].total_ms+=Number(r.ms)||0;traces[k].max_ms=Math.max(traces[k].max_ms,Number(r.ms)||0)}catch{issues.push(`invalid JSON: line ${i+1}`)}});return JSON.stringify({traces,issues},null,2)}
function srt(text){const cues=[],issues=[];text.trim().split(/\n\s*\n/).forEach((b,i)=>{const lines=b.split('\n'),t=lines.find(x=>x.includes('-->'));if(!t){issues.push(`block ${i+1}: timing missing`);return}const[a,z]=t.split('-->').map(x=>x.trim()),start=parseTime(a),end=parseTime(z);cues.push({start,end});if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)issues.push(`block ${i+1}: invalid timing`)});for(let i=1;i<cues.length;i++){if(cues[i].start<cues[i-1].end)issues.push(`cue ${i+1}: overlap ${cues[i-1].end-cues[i].start}ms`);const gap=cues[i].start-cues[i-1].end;if(gap>3000)issues.push(`cue ${i+1}: long gap ${gap}ms`)}return JSON.stringify({cues:cues.length,issues},null,2)}
function retry(text){const x=JSON.parse(text),a=Math.max(1,+x.attempts||1),b=Math.max(0,+x.base_ms||0),c=Math.max(1,+x.concurrency||1),p=Math.min(1,Math.max(0,+x.success_rate||0));let backoff=0;for(let i=0;i<a-1;i++)backoff+=b*(2**i);return JSON.stringify({attempts:a,backoff_ms:backoff,max_request_pressure:c*a,eventual_success_pct:+((1-(1-p)**a)*100).toFixed(2)},null,2)}
function csv(text){const rows=text.trim().split('\n').map(r=>r.split(',').map(c=>c.trim())),head=rows.shift()||[],unique=[],seen=new Set();let dup=0,missing=0;rows.forEach(r=>{const k=r.join('␟');if(seen.has(k)){dup++;return}seen.add(k);if(r.some(x=>!x))missing++;unique.push(r)});return `rows in: ${rows.length}\nrows out: ${unique.length}\nduplicates removed: ${dup}\nrows with empty cells: ${missing}\n\n${[head,...unique].map(r=>r.join(',')).join('\n')}`}
const f={trace,srt,retry,csv};function exec(){try{output.textContent=f[mode](input.value)}catch(e){output.textContent=`error: ${e.message}`}}tabs.forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;tabs.forEach(x=>x.classList.toggle('active',x===b));input.value=samples[mode];exec()}));run.addEventListener('click',exec);input.value=samples[mode];exec();
fetch('https://api.github.com/users/paper-daemon/repos?per_page=100&sort=updated').then(r=>r.ok?r.json():Promise.reject()).then(rs=>{const own=rs.filter(r=>!r.fork),latest=[...own].sort((a,b)=>new Date(b.pushed_at)-new Date(a.pushed_at))[0];const rc=document.querySelector('#repo-count'),p=document.querySelector('#github-pulse');if(rc)rc.textContent=own.length;if(p)p.textContent=`${own.length} public repos · latest: ${latest?.name||'—'}`}).catch(()=>{});
})();