(() => {
const samples={trace:`{"trace_id":"a1","event_id":"e1","step":"fetch","ms":120}\n{"trace_id":"a1","event_id":"e2","step":"transform","ms":860}\n{"trace_id":"a1","event_id":"e2","step":"transform","ms":860}\nnot-json`,srt:`1\n00:00:00,000 --> 00:00:02,400\n最初の字幕\n\n2\n00:00:02,200 --> 00:00:05,800\n少し重なる字幕\n\n3\n00:00:09,800 --> 00:00:13,000\n長い空白のあと`,retry:`{"attempts":4,"base_ms":400,"concurrency":6,"success_rate":0.68}`,csv:`name,email,note\nAlice,alice@example.com,"hello, world"\nBob,bob@example.com,"line 1\nline 2"\nAlice,alice@example.com,"hello, world"\nCharlie,,ok`};
const input=document.querySelector('#lab-input'),output=document.querySelector('#lab-output'),run=document.querySelector('#lab-run'),tabs=[...document.querySelectorAll('[data-mode]')];
const pulse=document.querySelector('#github-pulse');if(pulse)pulse.textContent='github.com/paper-daemon';
if(!input||!output)return;let mode='trace';
const MAX_LAB_INPUT_CHARS=200000;
const parseTime=s=>{const m=s.match(/(\d\d):(\d\d):(\d\d),(\d\d\d)/);return m?(((+m[1]*60 + +m[2])*60 + +m[3])*1000 + +m[4]):NaN};
const boundedNumber=(value,name,min,max,{integer=false}={})=>{const n=Number(value);if(!Number.isFinite(n))throw new Error(`${name} must be finite`);const v=integer?Math.trunc(n):n;if(v<min||v>max)throw new Error(`${name} must be between ${min} and ${max}`);return v};
function trace(text){const seen=new Set(),traces={},issues=[];text.split(/\n+/).filter(Boolean).forEach((line,i)=>{try{const r=JSON.parse(line),id=r.event_id||`line-${i+1}`,k=r.trace_id||'unknown';if(seen.has(id))issues.push(`duplicate event_id: ${id}`);seen.add(id);traces[k]??={events:0,total_ms:0,max_ms:0};traces[k].events++;traces[k].total_ms+=Number(r.ms)||0;traces[k].max_ms=Math.max(traces[k].max_ms,Number(r.ms)||0)}catch{issues.push(`invalid JSON: line ${i+1}`)}});return JSON.stringify({traces,issues},null,2)}
function srt(text){const cues=[],issues=[];text.trim().split(/\n\s*\n/).forEach((b,i)=>{const lines=b.split('\n'),t=lines.find(x=>x.includes('-->'));if(!t){issues.push(`block ${i+1}: timing missing`);return}const[a,z]=t.split('-->').map(x=>x.trim()),start=parseTime(a),end=parseTime(z);cues.push({start,end});if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)issues.push(`block ${i+1}: invalid timing`)});for(let i=1;i<cues.length;i++){if(cues[i].start<cues[i-1].end)issues.push(`cue ${i+1}: overlap ${cues[i-1].end-cues[i].start}ms`);const gap=cues[i].start-cues[i-1].end;if(gap>3000)issues.push(`cue ${i+1}: long gap ${gap}ms`)}return JSON.stringify({cues:cues.length,issues},null,2)}
function retry(text){const x=JSON.parse(text),a=boundedNumber(x.attempts,'attempts',1,12,{integer:true}),b=boundedNumber(x.base_ms,'base_ms',0,600000),c=boundedNumber(x.concurrency,'concurrency',1,10000),p=boundedNumber(x.success_rate,'success_rate',0,1);let backoff=0;for(let i=0;i<a-1;i++)backoff+=b*(2**i);const pressure=c*a,eventual=(1-(1-p)**a)*100;if(!Number.isFinite(backoff)||!Number.isFinite(pressure)||!Number.isFinite(eventual))throw new Error('retry calculation overflow');return JSON.stringify({attempts:a,backoff_ms:backoff,max_request_pressure:pressure,eventual_success_pct:+eventual.toFixed(2)},null,2)}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'){if(text[i+1]==='"'){cell+='"';i++}else quoted=false}else cell+=ch;continue}if(ch==='"'&&cell===''){quoted=true;continue}if(ch===','){row.push(cell.trim());cell='';continue}if(ch==='\n'){row.push(cell.trim());rows.push(row);row=[];cell='';continue}if(ch==='\r'&&text[i+1]==='\n')continue;cell+=ch}if(quoted)throw new Error('unterminated quoted field');if(cell!==''||row.length){row.push(cell.trim());rows.push(row)}return rows}
function csv(text){const rows=parseCsv(text.trim()),head=rows.shift()||[],unique=[],seen=new Set();let dup=0,missing=0;rows.forEach(r=>{const k=JSON.stringify(r);if(seen.has(k)){dup++;return}seen.add(k);if(r.some(x=>!x))missing++;unique.push(r)});const quote=v=>/[",\n\r]/.test(v)?`"${v.replace(/"/g,'""')}"`:v;return `rows in: ${rows.length}\nrows out: ${unique.length}\nduplicates removed: ${dup}\nrows with empty cells: ${missing}\n\n${[head,...unique].map(r=>r.map(quote).join(',')).join('\n')}`}
const f={trace,srt,retry,csv};function exec(){try{if(input.value.length>MAX_LAB_INPUT_CHARS)throw new Error(`input too large; max ${MAX_LAB_INPUT_CHARS} characters`);output.textContent=f[mode](input.value)}catch(e){output.textContent=`error: ${e.message}`}}tabs.forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;tabs.forEach(x=>x.classList.toggle('active',x===b));input.value=samples[mode];exec()}));run.addEventListener('click',exec);input.value=samples[mode];exec();
})();