(() => {
  const css = `
.live-lab{margin:72px -18px 0;padding:28px 28px 24px;background:#17191d;color:#f6f1e8;border-radius:26px;box-shadow:0 18px 45px rgba(35,28,24,.18)}
.lab-head{display:grid;grid-template-columns:1fr auto;gap:24px;align-items:start}.lab-kicker{margin:0 0 6px;font:700 .68rem/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.12em;color:#9fd8bf}.lab-head h2{margin:0;font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','Noto Serif JP',serif;font-size:clamp(2rem,5vw,3.6rem);line-height:1.08;color:#fff8ed}.lab-head p{max-width:610px;margin:10px 0 0;color:#bfc4c7;font-size:.85rem}
.github-pulse{min-width:160px;padding:13px 15px;border:1px solid #ffffff24;border-radius:14px;background:#ffffff09}.github-pulse b,.github-pulse span{display:block}.github-pulse b{font:700 .78rem/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;color:#fff}.github-pulse span{margin-top:4px;color:#9fd8bf;font-size:.68rem}
.lab-tabs{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0 12px}.lab-tabs button{appearance:none;border:1px solid #ffffff24;background:#ffffff08;color:#d5d9da;padding:8px 12px;border-radius:999px;font:650 .72rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;cursor:pointer}.lab-tabs button:hover,.lab-tabs button.is-active{background:#f6f1e8;color:#17191d;border-color:#f6f1e8}
.lab-console{display:grid;grid-template-columns:1fr 1fr;gap:12px}.lab-console>div{position:relative;min-width:0}.lab-console label{display:block;margin:0 0 6px;color:#8e979b;font:600 .65rem/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase}.lab-console textarea,.lab-console pre{box-sizing:border-box;width:100%;height:250px;margin:0;padding:16px;border:1px solid #ffffff18;border-radius:14px;background:#0d0f12;color:#dff5e7;font:500 .73rem/1.65 ui-monospace,SFMono-Regular,Menlo,monospace;resize:vertical;overflow:auto;white-space:pre-wrap}.lab-console pre[data-state="error"]{color:#ffb4b4}.lab-run{position:absolute;right:10px;bottom:10px;border:0;border-radius:999px;background:#9fd8bf;color:#10231a;padding:8px 12px;font:800 .68rem/1 ui-monospace,SFMono-Regular,Menlo,monospace;cursor:pointer;box-shadow:0 4px 14px #0005}.lab-run:hover{transform:translateY(-1px)}.lab-foot{margin:12px 2px 0;color:#8e979b;font-size:.69rem}.lab-foot a{color:#dff5e7}
.proof-wall{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0 0}.proof-wall a{display:block;min-height:170px;padding:18px 18px 20px;color:var(--memo-ink);text-decoration:none;border:1px solid #d7cabb;background:#f6edda;transition:transform .15s ease,box-shadow .15s ease}.proof-wall a:nth-child(2){background:#edf0e7;border-color:#ccd4c1}.proof-wall a:nth-child(3){background:#f8e7e9;border-color:#e3c6cc}.proof-wall a:hover{transform:translateY(-3px);box-shadow:3px 6px 0 rgba(82,65,54,.08)}.proof-wall span{display:block;color:var(--memo-muted);font:700 .62rem/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;letter-spacing:.08em}.proof-wall strong{display:block;margin:8px 0 9px;font-family:'Hiragino Mincho ProN','Yu Mincho','YuMincho','Noto Serif JP',serif;font-size:1.12rem;line-height:1.4}.proof-wall p{margin:0;color:#645950;font-size:.76rem;line-height:1.75}
@media(max-width:800px){.live-lab{margin-left:0;margin-right:0}.proof-wall{grid-template-columns:1fr 1fr}.proof-wall a:last-child{grid-column:1/-1}}@media(max-width:600px){.live-lab{margin-top:52px;padding:22px 17px 18px;border-radius:18px}.lab-head{grid-template-columns:1fr}.github-pulse{width:max-content}.lab-console{grid-template-columns:1fr}.lab-console textarea,.lab-console pre{height:220px}.proof-wall{grid-template-columns:1fr}.proof-wall a:last-child{grid-column:auto}}
`;
  const style = document.createElement('style'); style.textContent = css; document.head.append(style);

  const samples = {
    trace: `{"trace_id":"a1","event_id":"e1","step":"fetch","ms":120}\n{"trace_id":"a1","event_id":"e2","step":"transform","ms":860}\n{"trace_id":"a1","event_id":"e2","step":"transform","ms":860}\nnot-json\n{"trace_id":"b7","event_id":"e9","step":"publish","ms":92}`,
    srt: `1\n00:00:00,000 --> 00:00:02,400\n最初の字幕\n\n2\n00:00:02,200 --> 00:00:05,800\n少し重なっている字幕\n\n3\n00:00:09,800 --> 00:00:13,000\nここは長い空白のあと`,
    retry: `{"attempts":4,"base_ms":400,"concurrency":6,"success_rate":0.68}`,
    csv: ` name , email , status\n Alice ,alice@example.com, ok\nBob,bob@example.com, pending\n Alice ,alice@example.com, ok\nCharlie, , ok`
  };
  const input=document.querySelector('#lab-input'), output=document.querySelector('#lab-output'), run=document.querySelector('#lab-run'), tabs=[...document.querySelectorAll('[data-lab]')];
  if(!input||!output||!run||!tabs.length)return; let mode='trace';
  const parseTime=s=>{const m=s.match(/(\d\d):(\d\d):(\d\d),(\d\d\d)/);return m?(((+m[1]*60 + +m[2])*60 + +m[3])*1000 + +m[4]):NaN};
  function traceDemo(text){const seen=new Set(),traces=new Map(),issues=[];text.split(/\n+/).filter(Boolean).forEach((line,i)=>{try{const row=JSON.parse(line),id=row.event_id||`line-${i+1}`;if(seen.has(id))issues.push(`duplicate event_id: ${id}`);seen.add(id);const key=row.trace_id||'unknown',t=traces.get(key)||{events:0,total_ms:0,max_ms:0};t.events++;t.total_ms+=Number(row.ms)||0;t.max_ms=Math.max(t.max_ms,Number(row.ms)||0);traces.set(key,t)}catch{issues.push(`invalid JSON: line ${i+1}`)}});return JSON.stringify({traces:Object.fromEntries(traces),issues},null,2)}
  function srtDemo(text){const blocks=text.trim().split(/\n\s*\n/),cues=[],issues=[];blocks.forEach((block,i)=>{const lines=block.split('\n'),timing=lines.find(x=>x.includes('-->'));if(!timing){issues.push(`block ${i+1}: timing missing`);return}const[a,b]=timing.split('-->').map(x=>x.trim()),start=parseTime(a),end=parseTime(b);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)issues.push(`block ${i+1}: invalid timing`);cues.push({n:i+1,start,end,text:lines.slice(lines.indexOf(timing)+1).join(' ')})});for(let i=1;i<cues.length;i++){if(cues[i].start<cues[i-1].end)issues.push(`cue ${i+1}: overlaps previous by ${cues[i-1].end-cues[i].start}ms`);const gap=cues[i].start-cues[i-1].end;if(gap>3000)issues.push(`cue ${i+1}: long gap ${gap}ms`)}return JSON.stringify({cues:cues.length,issues},null,2)}
  function retryDemo(text){const x=JSON.parse(text),attempts=Math.max(1,Number(x.attempts)||1),base=Math.max(0,Number(x.base_ms)||0),c=Math.max(1,Number(x.concurrency)||1),p=Math.min(1,Math.max(0,Number(x.success_rate)||0));let backoff=0;for(let i=0;i<attempts-1;i++)backoff+=base*(2**i);const eventual=1-((1-p)**attempts);return JSON.stringify({attempts,backoff_ms:backoff,max_request_pressure:c*attempts,eventual_success_pct:+(eventual*100).toFixed(2)},null,2)}
  function csvDemo(text){const rows=text.trim().split('\n').map(r=>r.split(',').map(c=>c.trim())),header=rows.shift()||[],unique=[],seen=new Set();let dup=0,missing=0;rows.forEach(r=>{const key=r.join('\u241f');if(seen.has(key)){dup++;return}seen.add(key);if(r.some(x=>!x))missing++;unique.push(r)});return `rows in: ${rows.length}\nrows out: ${unique.length}\nduplicates removed: ${dup}\nrows with empty cells: ${missing}\n\n${[header,...unique].map(r=>r.join(',')).join('\n')}`}
  function execute(){try{output.textContent=({trace:traceDemo,srt:srtDemo,retry:retryDemo,csv:csvDemo})[mode](input.value);output.dataset.state='ok'}catch(e){output.textContent=`error: ${e.message}`;output.dataset.state='error'}}
  tabs.forEach(btn=>btn.addEventListener('click',()=>{mode=btn.dataset.lab;tabs.forEach(x=>x.classList.toggle('is-active',x===btn));input.value=samples[mode];execute()}));run.addEventListener('click',execute);input.value=samples[mode];execute();
  const pulse=document.querySelector('#github-pulse');if(pulse)fetch('https://api.github.com/users/paper-daemon/repos?per_page=100&sort=updated').then(r=>r.ok?r.json():Promise.reject(new Error(r.status))).then(repos=>{const own=repos.filter(r=>!r.fork),latest=own.sort((a,b)=>new Date(b.pushed_at)-new Date(a.pushed_at))[0];pulse.innerHTML=`<b>${own.length} public repos</b><span>latest: ${latest?latest.name:'—'}</span>`}).catch(()=>{pulse.innerHTML='<b>GitHub</b><span>public build log ↗</span>'});
})();
