(()=>{
'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const sleep=ms=>new Promise(r=>setTimeout(r,reduced?Math.min(ms,90):ms));
const rand=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const pick=a=>a[Math.floor(Math.random()*a.length)];
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hash=s=>{let h=5381;for(const c of s)h=((h*33)^c.charCodeAt(0))>>>0;return h.toString(16).slice(-6)};
function line(svgSel,arr,colorClass=''){const svg=$(svgSel);if(!svg)return;const p=$('polyline',svg);if(!p)return;const max=Math.max(1,...arr),min=Math.min(0,...arr);p.setAttribute('points',arr.map((v,i)=>`${i/(arr.length-1)*240},${74-(v-min)/(max-min||1)*66}`).join(' '));p.setAttribute('class',`live-line ${colorClass}`)}
function ioStart(root,start){if(!('IntersectionObserver'in window)){start();return}let started=false;const io=new IntersectionObserver(es=>{for(const e of es){if(e.isIntersecting&&!started){started=true;start();io.disconnect()}}},{threshold:.18});io.observe(root)}
function appendLog(box,text,cls=''){if(!box)return;const p=document.createElement('p');p.className=cls;p.textContent=text;box.appendChild(p);while(box.children.length>60)box.firstChild.remove();box.scrollTop=box.scrollHeight}
function bump(el,text){if(!el)return;const t=String(text);if(el.textContent!==t){el.textContent=t;el.classList.remove('bump');void el.offsetWidth;el.classList.add('bump')}}

/* ---------------------------------------------------------
   CREATIVE FACTORY / continuous candidate swarm
--------------------------------------------------------- */
const creativeRoot=$('#demo-creative');
if(creativeRoot){
 creativeRoot.className='flagship-demo live-lab creative-live';
 creativeRoot.innerHTML=`
 <header class="demo-heading live-heading"><div><p>02 / CREATIVE FACTORY / LIVE SIMULATION</p><h2>作り続けて、<br>悪い所だけ直す。</h2></div><div class="demo-copy"><b>候補生成・多軸評価・QA・差分修正・納品パックを止めずに回します。</b><br>右から事故を足すと、壊れた候補だけ隔離され、正常な候補はそのまま先へ進みます。</div></header>
 <div class="live-shell creative-shell">
  <div class="live-topbar"><div id="cf-live" class="live-status paused"><i></i><span>PAUSED</span><em id="cf-clock">00:00</em></div><div class="live-actions"><button id="cf-start" class="primary">生成ラインを開始</button><button id="cf-chaos">AUTO FAULT</button><button id="cf-reset">RESET</button></div></div>
  <div class="live-metrics creative-metrics"><div><small>GENERATED</small><b id="cf-gen">0</b><em>candidates</em></div><div><small>SHORTLIST</small><b id="cf-short">0</b><em>kept</em></div><div><small>REPAIRED</small><b id="cf-repair">0</b><em>differential</em></div><div><small>PACKAGED</small><b id="cf-pack">0</b><em>final assets</em></div><div><small>AVG SCORE</small><b id="cf-score">0</b><em>/ 100</em></div><div><small>QA LOAD</small><b id="cf-load">0%</b><em>rolling</em></div></div>
  <div class="creative-theater">
   <aside class="creative-brief"><header><small>BRIEF / LOCKED</small><b>PRODUCT VISUAL × 6</b></header><dl><div><dt>FORMAT</dt><dd>1:1 / PNG</dd></div><div><dt>LAYOUT</dt><dd>center / 12% air</dd></div><div><dt>TEXT</dt><dd>none</dd></div><div><dt>IDENTITY</dt><dd>same product</dd></div><div><dt>DELIVERY</dt><dd>6 finals + manifest</dd></div></dl><div class="constraint-bars"><span><i style="--v:94%"></i><b>composition</b></span><span><i style="--v:91%"></i><b>identity</b></span><span><i style="--v:96%"></i><b>format</b></span><span><i style="--v:88%"></i><b>style</b></span></div></aside>
   <div class="creative-stage"><div class="stage-label"><span>CANDIDATE SWARM / QA GATES</span><b id="cf-stage-state">waiting</b></div><div id="cf-wall" class="candidate-wall"></div><div class="creative-gates"><span>GENERATE</span><span>RANK</span><span>QA</span><span>REPAIR</span><span>PACKAGE</span></div></div>
   <aside class="fault-rail creative-faults"><header><small>FAULT INJECTION</small><b>制作事故を混ぜる。</b></header><button data-cf="identity"><b>形状をズラす</b><small>identity drift ×2</small></button><button data-cf="text"><b>不要文字を出す</b><small>text artifact ×2</small></button><button data-cf="crop"><b>構図をはみ出す</b><small>crop overflow ×2</small></button><button data-cf="style"><b>色調を外す</b><small>style drift ×2</small></button><button data-cf="seed"><b>同じseedを重ねる</b><small>duplicate candidate ×3</small></button><div id="cf-fault-readout" class="fault-readout">NO PENDING FAULT</div></aside>
  </div>
  <div class="live-telemetry creative-telemetry"><section><header><small>QUALITY SCORE / 30 EVENTS</small><b id="cf-q-now">0</b></header><svg id="cf-q-chart" class="live-chart" viewBox="0 0 240 80" preserveAspectRatio="none"><path d="M0 20H240M0 40H240M0 60H240"/><polyline points=""/></svg></section><section><header><small>QA EVENT LOG</small><b>LIVE</b></header><div id="cf-log" class="live-log"><p>waiting / line paused</p></div></section><section><header><small>DELIVERY PACK</small><b id="cf-pack-state">EMPTY</b></header><div id="cf-delivery" class="mini-ledger"><p>waiting for final assets</p></div></section></div>
  <div class="live-note"><strong>正常な候補は止めない。落ちた候補だけ隔離して、必要な差分だけ作り直す。</strong><span>LOCAL SIMULATION</span></div>
 </div>`;
 const wall=$('#cf-wall'),log=$('#cf-log'),ledger=$('#cf-delivery'),status=$('#cf-live');
 let epoch=1,running=false,auto=false,timer=null,autoTimer=null,startAt=performance.now(),seq=1;
 const st={gen:0,short:0,repair:0,pack:0,scores:[],hist:Array(30).fill(0),pending:{identity:0,text:0,crop:0,style:0,seed:0},active:0,seenSeeds:new Set()};
 const sync=()=>{bump($('#cf-gen'),st.gen);bump($('#cf-short'),st.short);bump($('#cf-repair'),st.repair);bump($('#cf-pack'),st.pack);bump($('#cf-score'),st.scores.length?Math.round(st.scores.slice(-30).reduce((a,b)=>a+b,0)/Math.min(30,st.scores.length)):0);bump($('#cf-load'),`${clamp(st.active*18,0,99)}%`);$('#cf-q-now').textContent=st.scores.length?st.scores.at(-1):0;line('#cf-q-chart',st.hist);const pending=Object.entries(st.pending).filter(([,v])=>v>0);$('#cf-fault-readout').innerHTML=pending.length?pending.map(([k,v])=>`<span>${k.toUpperCase()} ×${v}</span>`).join(''):'NO PENDING FAULT';$('#cf-pack-state').textContent=st.pack?`${st.pack} READY`:'EMPTY'};
 function setStatus(text,cls=''){status.className=`live-status ${cls}`.trim();$('span',status).textContent=text}
 function tick(){if(!running)return;const s=Math.floor((performance.now()-startAt)/1000);$('#cf-clock').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 function consumeFault(){for(const k of ['identity','text','crop','style','seed'])if(st.pending[k]>0){st.pending[k]--;return k}return Math.random()<.08?pick(['identity','text','crop','style']):''}
 async function spawn(){if(!running)return;const e=epoch,id=`V${String(seq++).padStart(3,'0')}`,fault=consumeFault(),seed=fault==='seed'&&st.seenSeeds.size?[...st.seenSeeds][0]:rand(1000,9999);st.seenSeeds.add(seed);st.gen++;st.active++;const base=rand(82,98),pen={identity:21,text:16,crop:14,style:12,seed:18}[fault]||0,score=clamp(base-pen+rand(-2,2),50,99);st.scores.push(score);st.hist.push(score);st.hist.shift();const card=document.createElement('article');card.className='candidate-card born';card.dataset.fault=fault;card.style.setProperty('--h',rand(18,42));card.innerHTML=`<span>${id}</span><b>${score}</b><i></i><small>seed ${seed}</small>`;wall.prepend(card);while(wall.children.length>24)wall.lastChild.remove();$('#cf-stage-state').textContent=`${id} / generated`;appendLog(log,`${id} generated / score ${score}${fault?` / ${fault} suspected`:''}`,fault?'warn':'');sync();await sleep(280);if(e!==epoch)return;
  if(fault){card.classList.add('qa-fail');appendLog(log,`${id} QA failed / ${fault} / isolated`,'warn');$('#cf-stage-state').textContent=`${id} / quarantine`;await sleep(420);if(e!==epoch)return;card.classList.add('repairing');appendLog(log,`${id} differential repair / preserving accepted regions`,'gold');await sleep(460);if(e!==epoch)return;card.classList.remove('qa-fail','repairing');card.classList.add('fixed','chosen');const fixed=clamp(score+rand(12,24),86,99);$('b',card).textContent=fixed;st.scores.push(fixed);st.hist.push(fixed);st.hist.shift();st.repair++;st.short++;appendLog(log,`${id} repair passed / ${fixed} / returned to shortlist`,'ok')}
  else if(score>=88){card.classList.add('chosen');st.short++;appendLog(log,`${id} shortlisted / quality gate PASS`,'ok')}
  else{card.classList.add('rejected');appendLog(log,`${id} rank below threshold / discarded`)}
  if(card.classList.contains('chosen')){await sleep(300);if(e!==epoch)return;card.classList.add('packaged');st.pack++;const row=document.createElement('p');row.innerHTML=`<i></i><span>${id}.png</span><b>${hash(id+score)}</b>`;ledger.prepend(row);while(ledger.children.length>8)ledger.lastChild.remove();appendLog(log,`${id} packaged / manifest receipt written`,'ok')}
  st.active--;sync();
 }
 function start(){if(running)return;running=true;startAt=performance.now();setStatus('RUNNING / GENERATING');$('#cf-start').textContent='PAUSE';appendLog(log,'continuous generation started','ok');timer=setInterval(spawn,reduced?900:680);spawn();sync()}
 function pause(){running=false;clearInterval(timer);timer=null;setStatus('PAUSED','paused');$('#cf-start').textContent='生成ラインを開始';appendLog(log,'line paused')}
 function reset(){epoch++;pause();auto=false;clearInterval(autoTimer);$('#cf-chaos').classList.remove('on');$('#cf-chaos').textContent='AUTO FAULT';Object.assign(st,{gen:0,short:0,repair:0,pack:0,scores:[],hist:Array(30).fill(0),pending:{identity:0,text:0,crop:0,style:0,seed:0},active:0,seenSeeds:new Set()});seq=1;wall.innerHTML='';log.innerHTML='<p>waiting / line paused</p>';ledger.innerHTML='<p>waiting for final assets</p>';sync()}
 $('#cf-start').addEventListener('click',()=>running?pause():start());$('#cf-reset').addEventListener('click',reset);$('#cf-chaos').addEventListener('click',()=>{auto=!auto;$('#cf-chaos').classList.toggle('on',auto);$('#cf-chaos').textContent=auto?'AUTO FAULT ON':'AUTO FAULT';clearInterval(autoTimer);if(auto){if(!running)start();autoTimer=setInterval(()=>{const k=pick(['identity','text','crop','style','seed']);st.pending[k]+=rand(1,2);appendLog(log,`fault injected / ${k}`,'warn');sync()},reduced?5000:3600)}});$$('[data-cf]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.cf;st.pending[k]+=k==='seed'?3:2;b.classList.add('active');setTimeout(()=>b.classList.remove('active'),650);appendLog(log,`manual fault / ${k} armed`,'warn');if(!running)start();sync()}));setInterval(tick,250);sync();ioStart(creativeRoot,start);
}

/* ---------------------------------------------------------
   DATA RESCUE / continuous dirty stream
--------------------------------------------------------- */
const dataRoot=$('#demo-data');
if(dataRoot){
 dataRoot.className='flagship-demo live-lab data-live';
 dataRoot.innerHTML=`
 <header class="demo-heading live-heading"><div><p>03 / DATA RESCUE / LIVE SIMULATION</p><h2>壊れたデータが、<br>流れ続ける。</h2></div><div class="demo-copy"><b>重複・欠損・型ズレ・schema driftを流し込みながら、正常行は止めません。</b><br>怪しい行だけ隔離し、修復・照合・lineage記録まで同時に進めます。</div></header>
 <div class="live-shell data-shell"><div class="live-topbar"><div id="dr-live" class="live-status paused"><i></i><span>PAUSED</span><em id="dr-clock">00:00</em></div><div class="live-actions"><button id="dr-start" class="primary">ストリーム開始</button><button id="dr-chaos">AUTO CONTAMINATION</button><button id="dr-reset">RESET</button></div></div>
 <div class="live-metrics"><div><small>INGESTED</small><b id="dr-in">0</b><em>rows</em></div><div><small>CLEAN OUT</small><b id="dr-out">0</b><em>rows</em></div><div><small>QUARANTINE</small><b id="dr-q">0</b><em>isolated</em></div><div><small>REPAIRED</small><b id="dr-r">0</b><em>rows</em></div><div><small>SCHEMA</small><b id="dr-schema">v3</b><em>active adapter</em></div><div><small>ERROR RATE</small><b id="dr-err">0%</b><em>rolling</em></div></div>
 <div class="data-theater"><div class="data-core"><div class="data-pipeline-live"><span>INGEST</span><span>PROFILE</span><span>DEDUPE</span><span>SCHEMA</span><span>REPAIR</span><span>RECONCILE</span><span>EXPORT</span></div><div id="dr-stream" class="row-stream"><div class="stream-lane"></div></div><div class="data-panels"><section><header><small>RECENT ROWS</small><b>STREAM</b></header><div id="dr-table" class="stream-table"></div></section><section><header><small>QUARANTINE BAY</small><b id="dr-bay-count">0</b></header><div id="dr-bay" class="quarantine-bay"><p>empty</p></div></section></div></div>
 <aside class="fault-rail data-faults"><header><small>CONTAMINATION</small><b>汚れを流し込む。</b></header><button data-dr="schema"><b>列構造を変える</b><small>schema drift ×3</small></button><button data-dr="dup"><b>重複を増やす</b><small>duplicate burst ×5</small></button><button data-dr="null"><b>NULLを撒く</b><small>null storm ×4</small></button><button data-dr="type"><b>型を崩す</b><small>currency/date ×4</small></button><button data-dr="encoding"><b>文字コードを壊す</b><small>encoding ×3</small></button><button data-dr="late"><b>遅延行を戻す</b><small>late arrival ×3</small></button><div id="dr-readout" class="fault-readout">STREAM CLEAN</div></aside></div>
 <div class="live-telemetry data-telemetry"><section><header><small>ERROR RATE / 30 EVENTS</small><b id="dr-e-now">0%</b></header><svg id="dr-chart" class="live-chart" viewBox="0 0 240 80" preserveAspectRatio="none"><path d="M0 20H240M0 40H240M0 60H240"/><polyline points=""/></svg></section><section><header><small>LINEAGE / RECONCILIATION</small><b>LIVE</b></header><div class="lineage-map"><span>SOURCE A<i></i></span><span>SOURCE B<i></i></span><b>→ PROFILE → REPAIR → EXPORT</b><em id="dr-reconcile">0 in / 0 out</em></div></section><section><header><small>EVENT LOG</small><b>LIVE</b></header><div id="dr-log" class="live-log"><p>waiting / stream paused</p></div></section></div>
 <div class="live-note"><strong>怪しい行を捨てない。原本・隔離・修復・出力件数が追える状態で残す。</strong><span>LOCAL SIMULATION</span></div></div>`;
 const log=$('#dr-log'),table=$('#dr-table'),bay=$('#dr-bay'),stream=$('#dr-stream'),status=$('#dr-live');let epoch=1,running=false,auto=false,timer=null,autoTimer=null,startAt=performance.now(),seq=1001;
 const st={in:0,out:0,q:0,r:0,issues:0,hist:Array(30).fill(0),pending:{schema:0,dup:0,null:0,type:0,encoding:0,late:0},active:0,schema:3};
 const sync=()=>{bump($('#dr-in'),st.in);bump($('#dr-out'),st.out);bump($('#dr-q'),st.q);bump($('#dr-r'),st.r);bump($('#dr-schema'),`v${st.schema}`);const er=st.in?Math.round(st.issues/st.in*100):0;bump($('#dr-err'),`${er}%`);$('#dr-e-now').textContent=`${er}%`;$('#dr-bay-count').textContent=st.q;$('#dr-reconcile').textContent=`${st.in} in / ${st.out} clean / ${st.q} isolated`;line('#dr-chart',st.hist,'amber');const p=Object.entries(st.pending).filter(([,v])=>v);$('#dr-readout').innerHTML=p.length?p.map(([k,v])=>`<span>${k.toUpperCase()} ×${v}</span>`).join(''):'STREAM CLEAN'};
 function setStatus(t,c=''){status.className=`live-status ${c}`.trim();$('span',status).textContent=t}
 function consume(){for(const k of ['schema','dup','null','type','encoding','late'])if(st.pending[k]>0){st.pending[k]--;return k}return Math.random()<.07?pick(['dup','null','type']):''}
 function addTable(id,issue,state){const r=document.createElement('p');r.className=state||'';r.innerHTML=`<span>${id}</span><span>${issue||'clean'}</span><span>${state||'PASS'}</span>`;table.prepend(r);while(table.children.length>10)table.lastChild.remove()}
 function addBay(id,issue){if(bay.textContent.trim()==='empty')bay.innerHTML='';const r=document.createElement('p');r.innerHTML=`<i></i><span>${id}</span><b>${issue}</b>`;bay.prepend(r);while(bay.children.length>7)bay.lastChild.remove()}
 async function fly(id,issue,e){if(reduced)return;const orb=document.createElement('span');orb.className=`row-orb ${issue?'bad':''}`;orb.textContent=id;stream.appendChild(orb);const y=rand(18,78);const anim=orb.animate([{transform:`translate(0,${y}px)`,opacity:.2},{offset:.15,opacity:1},{transform:`translate(calc(100% + 120px),${y}px)`,opacity:1}],{duration:issue?1450:1050,easing:'linear',fill:'forwards'});try{await anim.finished}catch{}if(e===epoch)orb.remove()}
 async function row(){if(!running)return;const e=epoch,id=seq++,issue=consume();st.in++;st.active++;if(issue)st.issues++;const er=Math.round(st.issues/st.in*100);st.hist.push(er);st.hist.shift();addTable(id,issue,issue?'WARN':'PASS');appendLog(log,`${id} ingest${issue?` / ${issue} detected`:' / clean'}`,issue?'warn':'');fly(id,issue,e);sync();await sleep(280);if(e!==epoch)return;
  if(issue==='dup'){st.q++;addBay(id,'DUPLICATE');appendLog(log,`${id} duplicate key / canonical preserved / duplicate isolated`,'gold');await sleep(260);st.q--;st.out++;appendLog(log,`${id} reconcile / duplicate effect avoided`,'ok')}
  else if(issue){st.q++;addBay(id,issue.toUpperCase());appendLog(log,`${id} moved to quarantine / original preserved`,'warn');await sleep(issue==='late'?700:420);if(e!==epoch)return;if(issue==='schema'){st.schema++;appendLog(log,`${id} schema adapter v${st.schema} generated / old reader kept`,'gold')}else if(issue==='encoding')appendLog(log,`${id} encoding normalized / byte source retained`,'gold');else if(issue==='late')appendLog(log,`${id} late event merged by event-time window`,'gold');else appendLog(log,`${id} ${issue} repaired from trusted source / rule applied`,'gold');st.r++;st.q--;st.out++;addTable(id,issue,'REPAIRED');appendLog(log,`${id} repaired / reconcile PASS / exported`,'ok')}
  else{st.out++;appendLog(log,`${id} exported / checksum ${hash(String(id))}`,'ok')}
  st.active--;sync();
 }
 function tick(){if(!running)return;const s=Math.floor((performance.now()-startAt)/1000);$('#dr-clock').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
 function start(){if(running)return;running=true;startAt=performance.now();setStatus('RUNNING / STREAM HEALTHY');$('#dr-start').textContent='PAUSE';appendLog(log,'continuous dirty-data stream started','ok');timer=setInterval(row,reduced?900:520);row()}
 function pause(){running=false;clearInterval(timer);timer=null;setStatus('PAUSED','paused');$('#dr-start').textContent='ストリーム開始';appendLog(log,'stream paused')}
 function reset(){epoch++;pause();auto=false;clearInterval(autoTimer);$('#dr-chaos').classList.remove('on');$('#dr-chaos').textContent='AUTO CONTAMINATION';Object.assign(st,{in:0,out:0,q:0,r:0,issues:0,hist:Array(30).fill(0),pending:{schema:0,dup:0,null:0,type:0,encoding:0,late:0},active:0,schema:3});seq=1001;table.innerHTML='';bay.innerHTML='<p>empty</p>';log.innerHTML='<p>waiting / stream paused</p>';sync()}
 $('#dr-start').addEventListener('click',()=>running?pause():start());$('#dr-reset').addEventListener('click',reset);$('#dr-chaos').addEventListener('click',()=>{auto=!auto;$('#dr-chaos').classList.toggle('on',auto);$('#dr-chaos').textContent=auto?'AUTO CONTAMINATION ON':'AUTO CONTAMINATION';clearInterval(autoTimer);if(auto){if(!running)start();autoTimer=setInterval(()=>{const k=pick(['schema','dup','null','type','encoding','late']);st.pending[k]+=rand(2,4);appendLog(log,`contamination injected / ${k}`,'warn');sync()},reduced?5200:3900)}});$$('[data-dr]').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.dr;st.pending[k]+={schema:3,dup:5,null:4,type:4,encoding:3,late:3}[k];appendLog(log,`manual contamination / ${k}`,'warn');b.classList.add('active');setTimeout(()=>b.classList.remove('active'),650);if(!running)start();sync()}));setInterval(tick,250);sync();ioStart(dataRoot,start);
}

/* ---------------------------------------------------------
   RESPONSIVE REPAIR / continuous multi-viewport scanner
--------------------------------------------------------- */
const webRoot=$('#demo-web');
if(webRoot){
 webRoot.className='flagship-demo live-lab web-live';
 webRoot.innerHTML=`
 <header class="demo-heading live-heading"><div><p>04 / RESPONSIVE REPAIR / LIVE SIMULATION</p><h2>壊しながら、<br>全画面を監視する。</h2></div><div class="demo-copy"><b>Desktop / Tablet / Mobileを同時に走査し、壊れたviewportだけ原因DOMまで追います。</b><br>複数の表示事故を重ねても、patch → retest → matrix PASSまで自動で戻します。</div></header>
 <div class="live-shell web-shell"><div class="live-topbar"><div id="wr-live" class="live-status"><i></i><span>SCANNING / HEALTHY</span><em id="wr-clock">00:00</em></div><div class="live-actions"><button id="wr-auto" class="primary">AUTO BREAK</button><button id="wr-scan">SCAN NOW</button><button id="wr-reset">RESET</button></div></div>
 <div class="live-metrics"><div><small>OPEN ISSUES</small><b id="wr-open">0</b><em>current</em></div><div><small>PATCHED</small><b id="wr-patched">0</b><em>repairs</em></div><div><small>RETESTS</small><b id="wr-retests">0</b><em>matrix runs</em></div><div><small>MAX OVERFLOW</small><b id="wr-over">0px</b><em>viewport</em></div><div><small>CLS</small><b id="wr-cls">0.00</b><em>rolling</em></div><div><small>MATRIX</small><b id="wr-matrix">9/9</b><em>checks pass</em></div></div>
 <div class="web-theater"><div class="viewport-core"><div id="wr-wall" class="viewport-wall">
  <article class="live-device desktop" data-vp="desktop"><header><b>DESKTOP</b><span>1440 × 900</span></header><div class="live-page"><nav></nav><section class="mock-hero"><div><h4></h4><p></p><p></p></div><i></i></section><div class="mock-cards"><b></b><b></b><b></b></div><div class="dom-box"></div></div></article>
  <article class="live-device tablet" data-vp="tablet"><header><b>TABLET</b><span>768 × 1024</span></header><div class="live-page"><nav></nav><section class="mock-hero"><div><h4></h4><p></p><p></p></div><i></i></section><div class="mock-cards"><b></b><b></b><b></b></div><div class="dom-box"></div></div></article>
  <article class="live-device mobile" data-vp="mobile"><header><b>MOBILE</b><span>390 × 844</span></header><div class="live-page"><nav></nav><section class="mock-hero"><div><h4></h4><p></p><p></p></div><i></i></section><div class="mock-cards"><b></b><b></b><b></b></div><div class="dom-box"></div></div></article>
 </div><div class="scan-beam"></div></div>
 <aside class="fault-rail web-faults"><header><small>BREAK THE PAGE</small><b>表示事故を重ねる。</b></header><button data-wr="overflow"><b>横幅を壊す</b><small>mobile overflow</small></button><button data-wr="cls"><b>レイアウトを跳ねる</b><small>CLS spike</small></button><button data-wr="font"><b>font fallback</b><small>metric shift</small></button><button data-wr="asset"><b>画像を欠損</b><small>broken asset</small></button><button data-wr="overlay"><b>UIを被せる</b><small>sticky collision</small></button><button data-wr="contrast"><b>contrastを落とす</b><small>a11y fail</small></button><div id="wr-readout" class="fault-readout">NO OPEN ISSUE</div></aside></div>
 <div class="web-bottom"><section class="test-matrix"><header><small>LIVE TEST MATRIX</small><b id="wr-test-state">ALL PASS</b></header><div class="matrix-grid"><span>DESKTOP / LAYOUT</span><span>DESKTOP / A11Y</span><span>DESKTOP / ASSET</span><span>TABLET / LAYOUT</span><span>TABLET / A11Y</span><span>TABLET / ASSET</span><span>MOBILE / LAYOUT</span><span>MOBILE / A11Y</span><span>MOBILE / ASSET</span></div></section><section class="patch-console"><header><small>PATCH DIFF</small><b id="wr-patch-state">IDLE</b></header><pre id="wr-patch">/* waiting for an issue */</pre></section><section><header class="sub-head"><small>EVENT LOG</small><b>LIVE</b></header><div id="wr-log" class="live-log"><p>scanner active / 3 viewports healthy</p></div></section></div>
 <div class="live-note"><strong>全部作り直さない。壊れたviewport・壊れたDOM・壊れたルールだけ直して、全matrixを再確認する。</strong><span>LOCAL SIMULATION</span></div></div>`;
 const log=$('#wr-log'),wall=$('#wr-wall'),status=$('#wr-live'),patch=$('#wr-patch');let epoch=1,auto=false,autoTimer=null,scanTimer=null,startAt=performance.now();const faults=new Map();const st={patched:0,retests:0,overflow:0,cls:0};
 const faultMeta={overflow:{vp:'mobile',cls:'fault-overflow',patch:'- grid-template-columns: 210px 130px;\n+ grid-template-columns: 1fr;\n- width: 551px;\n+ width: auto;'},cls:{vp:'tablet',cls:'fault-cls',patch:'- min-height: auto;\n+ min-height: 18rem;\n+ aspect-ratio: 16 / 9;'},font:{vp:'mobile',cls:'fault-font',patch:'- font-family: fallback;\n+ font-family: var(--serif);\n+ font-size-adjust: .52;'},asset:{vp:'desktop',cls:'fault-asset',patch:'- background-image: url(missing);\n+ background: var(--asset-fallback);'},overlay:{vp:'mobile',cls:'fault-overlay',patch:'- position: fixed; bottom: 0;\n+ position: sticky;\n+ padding-bottom: env(safe-area-inset-bottom);'},contrast:{vp:'tablet',cls:'fault-contrast',patch:'- color: #c7bdb2;\n+ color: #4c4036;'}};
 function sync(){const open=faults.size;bump($('#wr-open'),open);bump($('#wr-patched'),st.patched);bump($('#wr-retests'),st.retests);bump($('#wr-over'),`${st.overflow}px`);bump($('#wr-cls'),st.cls.toFixed(2));bump($('#wr-matrix'),`${9-Math.min(9,open)}/9`);$('#wr-readout').innerHTML=open?[...faults.keys()].map(k=>`<span>${k.toUpperCase()}</span>`).join(''):'NO OPEN ISSUE';const cells=$$('.matrix-grid span');cells.forEach(c=>c.className='pass');for(const [k,m] of faults){const vp=m.vp.toUpperCase();cells.filter(c=>c.textContent.startsWith(vp)).forEach((c,i)=>{if(k==='contrast'&&i===1||k==='asset'&&i===2||!['contrast','asset'].includes(k)&&i===0)c.className='fail'})}$('#wr-test-state').textContent=open?`${open} ISSUE${open>1?'S':''}`:'ALL PASS';status.className=`live-status ${open?'warn':''}`;$('span',status).textContent=open?'SCANNING / DEGRADED':'SCANNING / HEALTHY'}
 function applyVisual(k,on){const m=faultMeta[k],d=$(`.live-device[data-vp="${m.vp}"]`);if(d)d.classList.toggle(m.cls,on);if(k==='overflow')st.overflow=on?161:0;if(k==='cls')st.cls=on?.23:0}
 function inject(k){if(faults.has(k))return;const m=faultMeta[k];faults.set(k,m);applyVisual(k,true);appendLog(log,`fault injected / ${k} / ${m.vp}`,'warn');$('#wr-patch-state').textContent='ISSUE DETECTED';patch.textContent='/* scanner locating cause… */';sync();setTimeout(()=>repair(k),reduced?180:900)}
 async function repair(k){if(!faults.has(k))return;const e=epoch,m=faults.get(k);appendLog(log,`trace / ${k} / computed style + DOM ancestry`,'gold');$('#wr-patch-state').textContent='PATCHING';patch.textContent=m.patch;await sleep(500);if(e!==epoch||!faults.has(k))return;applyVisual(k,false);faults.delete(k);st.patched++;st.retests++;appendLog(log,`patch applied / ${k} / ${m.vp}`,'ok');await sleep(260);if(e!==epoch)return;appendLog(log,`retest / ${m.vp} PASS / matrix updated`,'ok');$('#wr-patch-state').textContent=faults.size?'NEXT ISSUE':'ALL PATCHED';sync()}
 function scan(){const beam=$('.scan-beam');beam.classList.remove('run');void beam.offsetWidth;beam.classList.add('run');if(faults.size)appendLog(log,`scan / ${faults.size} open issue(s) / patch queue active`,'warn');else if(Math.random()<.3)appendLog(log,'scan / 3 viewports / 9 checks PASS')}
 function reset(){epoch++;faults.clear();for(const k of Object.keys(faultMeta))applyVisual(k,false);st.patched=st.retests=st.overflow=st.cls=0;patch.textContent='/* waiting for an issue */';$('#wr-patch-state').textContent='IDLE';log.innerHTML='<p>scanner active / 3 viewports healthy</p>';auto=false;clearInterval(autoTimer);$('#wr-auto').classList.remove('on');$('#wr-auto').textContent='AUTO BREAK';sync()}
 $$('[data-wr]').forEach(b=>b.addEventListener('click',()=>{inject(b.dataset.wr);b.classList.add('active');setTimeout(()=>b.classList.remove('active'),650)}));$('#wr-scan').addEventListener('click',scan);$('#wr-reset').addEventListener('click',reset);$('#wr-auto').addEventListener('click',()=>{auto=!auto;$('#wr-auto').classList.toggle('on',auto);$('#wr-auto').textContent=auto?'AUTO BREAK ON':'AUTO BREAK';clearInterval(autoTimer);if(auto)autoTimer=setInterval(()=>inject(pick(Object.keys(faultMeta))),reduced?4800:3200)});scanTimer=setInterval(scan,reduced?5000:2400);setInterval(()=>{const s=Math.floor((performance.now()-startAt)/1000);$('#wr-clock').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`},250);sync();ioStart(webRoot,()=>{$('#wr-auto').click()});
}
})();