(()=>{
const host=document.querySelector('#demo-ops');if(!host)return;
if(!document.querySelector('link[href="/ops-theater.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='/ops-theater.css';document.head.appendChild(l)}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const nodes=[
 ['ingress','01 / INGRESS','REQUEST','jobs arrive','7%','48%',''],['queue','02 / QUEUE','DURABLE QUEUE','backpressure','19%','48%',''],['router','03 / ROUTER','ROUTER','health / lock / load','31%','48%',''],
 ['worker-a','04A / WORKER','WORKER A','creative / cap 2','46%','18%','worker'],['worker-b','04B / WORKER','WORKER B','sync / cap 2','46%','38%','worker'],['worker-c','04C / RESERVE','WORKER C','fallback / cap 1','46%','60%','worker reserve'],['worker-d','04D / LOCAL','WORKER D','local / cap 1','46%','80%','worker'],
 ['qa','05 / QA','VALIDATE','schema / format / safety','64%','34%',''],['quarantine','05B / QUARANTINE','REPAIR BAY','bad payload only','64%','73%','quarantine'],['delivery','06 / DELIVERY','DELIVERY','effect request','78%','34%',''],['remote','07 / REMOTE','REMOTE API','ack / 429 / timeout','91%','34%',''],['reconcile','07B / RECONCILE','RECONCILE','did effect happen?','79%','72%',''],['receipt','08 / RECEIPT','RECEIPT','effect ledger','92%','72%','good'],['guard','03B / GUARD','IDEMPOTENCY','duplicate stop','31%','78%','guard']
];
const edges=[['ingress','queue'],['queue','router'],['router','worker-a'],['router','worker-b'],['router','worker-c'],['router','worker-d'],['router','guard'],['worker-a','qa'],['worker-b','qa'],['worker-c','qa'],['worker-d','qa'],['qa','delivery'],['qa','quarantine'],['quarantine','qa'],['delivery','remote'],['remote','receipt'],['remote','reconcile'],['reconcile','receipt'],['reconcile','delivery']];
const nodeHtml=nodes.map(([id,k,t,s,x,y,c])=>`<article id="ot-${id}" class="topology-node ${c}" style="--x:${x};--y:${y}"><small>${k}</small><strong>${t}</strong><span>${s}</span>${c.includes('worker')?'<div class="node-load"><i></i></div>':''}</article>`).join('');
host.className='resilience-theater';host.innerHTML=`
<header class="theater-intro"><div><p>01 / RESILIENCE THEATER / LOCAL SIMULATION</p><h2>運用中に、<br>事故を入れる。</h2></div><div class="copy"><b>これは一回再生して終わるアニメではありません。</b><br>ジョブが流れ続ける小さな運用システムです。右から障害を好きに注入すると、経路・queue・worker負荷・p95・circuit・receiptが連動して変わります。</div></header>
<div class="theater-shell"><div class="theater-topbar"><div id="ot-live" class="theater-live paused"><i></i><span>PAUSED</span><span id="ot-clock" class="theater-clock">00:00.0</span></div><div class="theater-actions"><button id="ot-start" class="primary">連続運転を開始</button><button id="ot-auto" class="auto-chaos">AUTO CHAOS</button><button id="ot-reset">RESET</button></div></div>
<div class="theater-metrics"><div class="theater-metric"><small>THROUGHPUT / MIN</small><b id="ot-through">0</b><em>completed</em></div><div class="theater-metric"><small>QUEUE DEPTH</small><b id="ot-queue">0</b><em>waiting</em></div><div class="theater-metric"><small>RUNNING</small><b id="ot-running">0</b><em>in flight</em></div><div class="theater-metric"><small>P95 LATENCY</small><b id="ot-p95">0.0s</b><em>rolling</em></div><div class="theater-metric"><small>RECOVERED</small><b id="ot-recovered">0</b><em>faults handled</em></div><div class="theater-metric"><small>DUP BLOCKED</small><b id="ot-blocked">0</b><em>effects avoided</em></div></div>
<div class="theater-main"><div class="topology-wrap"><div id="ot-map" class="topology-map"><svg id="ot-svg" class="topology-svg" aria-hidden="true"></svg>${nodeHtml}<div class="map-legend"><span><i></i> route</span><span class="r"><i></i> incident</span><span class="g"><i></i> recovered</span></div></div></div><aside class="incident-rail"><header><small>FAULT INJECTION</small><b>好きに壊せます。</b></header><div class="incident-list">
<button class="incident-btn" data-incident="worker"><b>Worker Aを落とす</b><em>7s</em><small>heartbeat loss / reroute</small></button><button class="incident-btn" data-incident="rate"><b>APIを429にする</b><em>6s</em><small>circuit open / backoff</small></button><button class="incident-btn" data-incident="duplicate"><b>重複を4発入れる</b><em>NOW</em><small>idempotency burst</small></button><button class="incident-btn" data-incident="corrupt"><b>payloadを壊す</b><em>×2</em><small>QA fail / repair bay</small></button><button class="incident-btn" data-incident="ack"><b>ACKを消す</b><em>×1</em><small>reconcile before retry</small></button><button class="incident-btn" data-incident="partition"><b>networkを分断</b><em>7s</em><small>B/C unreachable</small></button><button class="incident-btn" data-incident="surge"><b>queueを急増</b><em>×12</em><small>backpressure test</small></button></div><div id="ot-incident-readout" class="incident-readout"><b>NO ACTIVE INCIDENT</b><br>continuous jobs are paused.</div></aside></div>
<div class="telemetry"><section class="telemetry-card"><header><small>QUEUE DEPTH / 30s</small><b id="ot-q-now">0</b></header><svg id="ot-q-chart" class="spark" viewBox="0 0 240 80" preserveAspectRatio="none"><path class="grid" d="M0 20H240M0 40H240M0 60H240"/><polyline class="line" points=""/></svg><div class="spark-caption"><span>30s ago</span><span>now</span></div></section><section class="telemetry-card"><header><small>P95 LATENCY / 30s</small><b id="ot-p-now">0.0s</b></header><svg id="ot-p-chart" class="spark" viewBox="0 0 240 80" preserveAspectRatio="none"><path class="grid" d="M0 20H240M0 40H240M0 60H240"/><polyline class="line blue" points=""/></svg><div class="spark-caption"><span>30s ago</span><span>now</span></div></section><section class="telemetry-card"><header><small>EVENT TIMELINE</small><b>LIVE</b></header><div id="ot-timeline" class="timeline"><p>waiting / start continuous run</p></div></section><section class="telemetry-card"><header><small>RECEIPT LEDGER</small><b>LOCAL</b></header><div id="ot-receipts" class="receipt-stack"><div class="theater-receipt"><i></i><span>waiting for effects</span><span class="hash">—</span></div></div></section></div>
<div class="theater-note"><strong>ポイント：事故を複数重ねても、止める場所・待つ場所・再試行する場所を分けています。</strong><span>SIMULATION / no external action / <a href="https://github.com/paper-daemon/AgentLink">AgentLinkを見る ↗</a></span></div></div>`;

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const map=$('#ot-map'),svg=$('#ot-svg'),timeline=$('#ot-timeline'),receiptBox=$('#ot-receipts');
let epoch=1,running=false,autoChaos=false,startedAt=performance.now(),jobSeq=2200,lastKey=null,generator=null,chaosTimer=null,tickTimer=null,historyTimer=null;
const state={queue:0,recovered:0,blocked:0,completed:[],latencies:[],qHist:Array(30).fill(0),pHist:Array(30).fill(0),flags:{corrupt:0,ack:0},incidents:{workerUntil:0,rateUntil:0,partitionUntil:0},seen:new Set(),active:new Map()};
const workers={a:{id:'worker-a',busy:0,cap:2,downUntil:0},b:{id:'worker-b',busy:0,cap:2,downUntil:0},c:{id:'worker-c',busy:0,cap:1,downUntil:0},d:{id:'worker-d',busy:0,cap:1,downUntil:0}};
const edgeMap=new Map();
function now(){return performance.now()}
function node(id){return $('#ot-'+id)}
function sleep(ms,e=epoch){return new Promise(r=>setTimeout(()=>r(e===epoch),reduced?Math.min(ms,90):ms))}
function ts(){const t=(now()-startedAt)/1000;return `${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(1).padStart(4,'0')}`}
function log(text,cls='on'){const p=document.createElement('p');p.className=cls;p.textContent=`${ts()}  ${text}`;timeline.appendChild(p);while(timeline.children.length>70)timeline.firstChild.remove();timeline.scrollTop=timeline.scrollHeight}
function bump(id,val){const el=$(id);if(!el)return;const txt=String(val);if(el.textContent!==txt){el.textContent=txt;el.classList.remove('bump');void el.offsetWidth;el.classList.add('bump')}}
function activeIncident(){const t=now();return t<state.incidents.workerUntil||t<state.incidents.rateUntil||t<state.incidents.partitionUntil||state.flags.corrupt>0||state.flags.ack>0}
function updateStatus(){const live=$('#ot-live');const span=live.querySelector('span');live.className='theater-live '+(!running?'paused':activeIncident()?'incident':'');span.textContent=!running?'PAUSED':activeIncident()?'RUNNING / DEGRADED':'RUNNING / HEALTHY';$('#ot-clock').textContent=ts()}
function hash(s){let h=5381;for(const c of s)h=((h*33)^c.charCodeAt(0))>>>0;return h.toString(16).slice(-6)}
function addReceipt(job,label='COMPLETED',cls=''){if(receiptBox.children.length===1&&receiptBox.textContent.includes('waiting'))receiptBox.innerHTML='';const row=document.createElement('div');row.className=`theater-receipt ${cls}`.trim();row.innerHTML=`<i></i><span>${job.id} / ${label}</span><span class="hash">${hash(job.id+label)}</span>`;receiptBox.prepend(row);while(receiptBox.children.length>8)receiptBox.lastChild.remove()}
function nodeClass(id,cls,on=true){const el=node(id);if(el)el.classList.toggle(cls,on)}
function workerVisible(){const t=now();for(const [k,w] of Object.entries(workers)){const el=node(w.id);if(!el)continue;const down=t<w.downUntil||(t<state.incidents.partitionUntil&&(k==='b'||k==='c'));el.classList.toggle('down',down);el.classList.toggle('active',w.busy>0&&!down);el.classList.toggle('awake',k==='c'&&w.busy>0);const bar=el.querySelector('.node-load i');if(bar)bar.style.setProperty('--load',`${Math.min(100,w.busy/w.cap*100)}%`);if(bar)bar.style.width=`${Math.min(100,w.busy/w.cap*100)}%`}}
function center(id){const el=node(id),mr=map.getBoundingClientRect();if(!el)return{x:0,y:0};const r=el.getBoundingClientRect();return{x:r.left-mr.left+r.width/2,y:r.top-mr.top+r.height/2}}
function drawEdges(){svg.innerHTML='';edgeMap.clear();for(const [a,b] of edges){const s=center(a),t=center(b),mid=(s.x+t.x)/2;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',`M${s.x},${s.y} C${mid},${s.y} ${mid},${t.y} ${t.x},${t.y}`);p.setAttribute('class','topology-edge flow');p.dataset.edge=`${a}>${b}`;svg.appendChild(p);edgeMap.set(`${a}>${b}`,p)}}
function pulseEdge(a,b,kind='ok'){const p=edgeMap.get(`${a}>${b}`);if(!p)return;p.classList.add(kind);setTimeout(()=>p.classList.remove(kind),700)}
async function move(job,a,b,kind='',duration=440,e=epoch){if(e!==epoch)return false;const from=center(a),to=center(b);pulseEdge(a,b,kind==='red'?'hot':'ok');nodeClass(b,'active',true);if(reduced){await sleep(60,e);nodeClass(b,'active',false);return e===epoch}const orb=document.createElement('span');orb.className=`job-orb ${kind}`.trim();orb.textContent=job.id.replace('J-','');map.appendChild(orb);const anim=orb.animate([{transform:`translate(${from.x}px,${from.y}px) translate(-50%,-50%)`,opacity:.25},{offset:.12,opacity:1},{transform:`translate(${to.x}px,${to.y}px) translate(-50%,-50%)`,opacity:1}],{duration,easing:'cubic-bezier(.2,.76,.2,1)',fill:'forwards'});try{await anim.finished}catch{}orb.remove();setTimeout(()=>nodeClass(b,'active',false),160);return e===epoch}
function p95(){const a=state.latencies.slice(-40).sort((x,y)=>x-y);if(!a.length)return 0;return a[Math.min(a.length-1,Math.floor(a.length*.95))]}
function throughput(){const cut=now()-60000;state.completed=state.completed.filter(x=>x>cut);return state.completed.length}
function metrics(){bump('#ot-through',throughput());bump('#ot-queue',state.queue);bump('#ot-running',state.active.size);bump('#ot-p95',`${p95().toFixed(1)}s`);bump('#ot-recovered',state.recovered);bump('#ot-blocked',state.blocked);$('#ot-q-now').textContent=state.queue;$('#ot-p-now').textContent=`${p95().toFixed(1)}s`;workerVisible();updateIncidentReadout();updateStatus();const t=now();nodeClass('remote','warn',t<state.incidents.rateUntil);nodeClass('router','warn',t<state.incidents.partitionUntil);if(t>=state.incidents.rateUntil)nodeClass('remote','warn',false);if(t>=state.incidents.partitionUntil)nodeClass('router','warn',false)}
function plot(id,arr){const poly=$(id)?.querySelector('polyline');if(!poly)return;const max=Math.max(1,...arr);poly.setAttribute('points',arr.map((v,i)=>`${i/(arr.length-1)*240},${76-v/max*68}`).join(' '))}
function sampleHistory(){state.qHist.push(state.queue);state.qHist.shift();state.pHist.push(p95());state.pHist.shift();plot('#ot-q-chart',state.qHist);plot('#ot-p-chart',state.pHist)}
function incidentButton(type,active){const b=$(`.incident-btn[data-incident="${type}"]`);if(b)b.classList.toggle('active',active)}
function updateIncidentReadout(){const t=now(),items=[];if(t<state.incidents.workerUntil)items.push(`<span class="warn">WORKER A DOWN ${(state.incidents.workerUntil-t)/1000|0}s</span>`);if(t<state.incidents.rateUntil)items.push(`<span class="warn">REMOTE API 429 ${(state.incidents.rateUntil-t)/1000|0}s / CIRCUIT OPEN</span>`);if(t<state.incidents.partitionUntil)items.push(`<span class="warn">NETWORK PARTITION ${(state.incidents.partitionUntil-t)/1000|0}s / B+C ISOLATED</span>`);if(state.flags.corrupt)items.push(`<span>PAYLOAD CORRUPTION ARMED ×${state.flags.corrupt}</span>`);if(state.flags.ack)items.push(`<span>ACK LOSS ARMED ×${state.flags.ack}</span>`);const box=$('#ot-incident-readout');box.innerHTML=items.length?`<b>ACTIVE INCIDENTS</b><br>${items.join('<br>')}`:`<b>NO ACTIVE INCIDENT</b><br>${running?'system healthy / inject anything':'continuous jobs are paused.'}`;incidentButton('worker',t<state.incidents.workerUntil);incidentButton('rate',t<state.incidents.rateUntil);incidentButton('partition',t<state.incidents.partitionUntil);incidentButton('corrupt',state.flags.corrupt>0);incidentButton('ack',state.flags.ack>0)}
function workerAvailable(k){const t=now(),w=workers[k];if(t<w.downUntil)return false;if(t<state.incidents.partitionUntil&&(k==='b'||k==='c'))return false;return w.busy<w.cap}
async function acquireWorker(job,e){for(let tries=0;tries<40&&e===epoch;tries++){const keys=Object.keys(workers).filter(workerAvailable).sort((a,b)=>workers[a].busy/workers[a].cap-workers[b].busy/workers[b].cap);if(keys.length)return keys[0];state.queue++;metrics();await sleep(180,e);state.queue=Math.max(0,state.queue-1)}return 'd'}
function complete(job,label='COMPLETED'){state.active.delete(job.id);state.completed.push(now());const latency=(now()-job.born)/1000;state.latencies.push(latency);if(state.latencies.length>80)state.latencies.shift();addReceipt(job,label);log(`${job.id} / ${label.toLowerCase()} / ${latency.toFixed(2)}s`,'ok');metrics()}
async function processJob(job,e=epoch){if(e!==epoch)return;state.active.set(job.id,job);state.queue++;metrics();await move(job,'ingress','queue','',330,e);if(e!==epoch)return;await sleep(120+Math.random()*280,e);state.queue=Math.max(0,state.queue-1);await move(job,'queue','router','',300,e);if(e!==epoch)return;
 if(state.seen.has(job.key)){await move(job,'router','guard','gold',300,e);state.blocked++;state.active.delete(job.id);addReceipt(job,'DUP BLOCKED','blocked');log(`${job.id} / duplicate key blocked before effect`,'gold');metrics();return}state.seen.add(job.key);lastKey=job.key;
 job.corrupt=state.flags.corrupt>0;if(job.corrupt)state.flags.corrupt--;job.ackLoss=state.flags.ack>0;if(job.ackLoss)state.flags.ack--;
 let wk=await acquireWorker(job,e);if(e!==epoch)return;let w=workers[wk];await move(job,'router',w.id,'',360,e);w.busy++;workerVisible();log(`${job.id} / ${w.id.toUpperCase()} started`,'on');await sleep(420+Math.random()*520,e);if(e!==epoch)return;
 const workerFailed=!workerAvailable(wk)&&w.busy>0;if(workerFailed){w.busy=Math.max(0,w.busy-1);workerVisible();state.recovered++;job.retries=(job.retries||0)+1;log(`${job.id} / ${w.id.toUpperCase()} unavailable / effect not committed`,'warn');await move(job,w.id,'router','red',420,e);wk=await acquireWorker(job,e);w=workers[wk];await move(job,'router',w.id,'gold',380,e);w.busy++;workerVisible();log(`${job.id} / rerouted to ${w.id.toUpperCase()} / retry ${job.retries}/2`,'gold');await sleep(450+Math.random()*350,e)}
 w.busy=Math.max(0,w.busy-1);workerVisible();await move(job,w.id,'qa','green',340,e);log(`${job.id} / QA started`,'on');await sleep(220,e);
 if(job.corrupt){log(`${job.id} / payload validation failed / quarantine`,'warn');await move(job,'qa','quarantine','red',320,e);await sleep(520,e);state.recovered++;log(`${job.id} / repair bay fixed schema + payload`,'gold');await move(job,'quarantine','qa','gold',360,e);await sleep(180,e)}
 await move(job,'qa','delivery','green',320,e);await sleep(120,e);
 if(now()<state.incidents.rateUntil){log(`${job.id} / remote 429 / circuit open / backoff`,'warn');await move(job,'delivery','reconcile','gold',340,e);const remain=Math.max(250,Math.min(3500,state.incidents.rateUntil-now()+120));await sleep(remain,e);state.recovered++;await move(job,'reconcile','delivery','gold',320,e)}
 await move(job,'delivery','remote','green',330,e);await sleep(160,e);
 if(job.ackLoss){log(`${job.id} / ACK missing / do not resend / reconcile first`,'warn');await move(job,'remote','reconcile','gold',360,e);await sleep(520,e);state.recovered++;log(`${job.id} / remote effect found / resend cancelled`,'gold');await move(job,'reconcile','receipt','green',340,e);complete(job,'RECONCILED')}else{await move(job,'remote','receipt','green',340,e);complete(job)}
}
function spawnJob(opts={}){if(!running&&!opts.force)return null;const id=`J-${jobSeq++}`,kind=['IMG','SYNC','WEB','DATA'][jobSeq%4],key=opts.key||`K-${id}`;const job={id,kind,key,born:now(),duplicate:!!opts.duplicate,retries:0};processJob(job,epoch);return job}
function inject(type,fromAuto=false){if(!running&&type!=='surge'){running=true;$('#ot-start').textContent='PAUSE';startedAt=now();log('continuous run auto-started','on')}const t=now();if(type==='worker'){state.incidents.workerUntil=t+7000;workers.a.downUntil=t+7000;log('FAULT / worker A heartbeat lost / 7s','warn')}if(type==='rate'){state.incidents.rateUntil=t+6000;log('FAULT / remote API returning 429 / circuit opened','warn')}if(type==='partition'){state.incidents.partitionUntil=t+7000;log('FAULT / network partition / workers B+C isolated','warn')}if(type==='corrupt'){state.flags.corrupt+=2;log('FAULT / next 2 payloads will fail QA','warn')}if(type==='ack'){state.flags.ack+=1;log('FAULT / next delivery ACK will disappear','warn')}if(type==='duplicate'){const key=lastKey||`K-SEED-${jobSeq}`;for(let i=0;i<4;i++)setTimeout(()=>spawnJob({key,duplicate:true,force:true}),i*120);log('FAULT / duplicate event burst ×4 injected','warn');incidentButton('duplicate',true);setTimeout(()=>incidentButton('duplicate',false),1100)}if(type==='surge'){if(!running){running=true;$('#ot-start').textContent='PAUSE';startedAt=now()}for(let i=0;i<12;i++)setTimeout(()=>spawnJob({force:true}),i*75);log('FAULT / queue surge ×12','warn');incidentButton('surge',true);setTimeout(()=>incidentButton('surge',false),1200)}if(fromAuto)log(`AUTO CHAOS / ${type}`,'gold');metrics()}
function start(){running=!running;$('#ot-start').textContent=running?'PAUSE':'連続運転を開始';if(running){if(!state.active.size&&!state.completed.length)startedAt=now();log('continuous run started / generator 1 job ~0.9s','on')}else log('simulation paused / in-flight jobs finish','gold');updateStatus()}
function toggleAuto(){autoChaos=!autoChaos;$('#ot-auto').classList.toggle('on',autoChaos);$('#ot-auto').textContent=autoChaos?'AUTO CHAOS ON':'AUTO CHAOS';log(autoChaos?'auto chaos enabled':'auto chaos disabled',autoChaos?'warn':'gold')}
function hardReset(){epoch++;running=false;autoChaos=false;startedAt=now();jobSeq=2200;lastKey=null;state.queue=0;state.recovered=0;state.blocked=0;state.completed=[];state.latencies=[];state.qHist=Array(30).fill(0);state.pHist=Array(30).fill(0);state.flags.corrupt=0;state.flags.ack=0;state.incidents.workerUntil=0;state.incidents.rateUntil=0;state.incidents.partitionUntil=0;state.seen.clear();state.active.clear();for(const w of Object.values(workers)){w.busy=0;w.downUntil=0}$$('.job-orb').forEach(x=>x.remove());receiptBox.innerHTML='<div class="theater-receipt"><i></i><span>waiting for effects</span><span class="hash">—</span></div>';timeline.innerHTML='<p>waiting / start continuous run</p>';$('#ot-start').textContent='連続運転を開始';$('#ot-auto').textContent='AUTO CHAOS';$('#ot-auto').classList.remove('on');plot('#ot-q-chart',state.qHist);plot('#ot-p-chart',state.pHist);metrics();drawEdges()}
$('#ot-start').addEventListener('click',start);$('#ot-auto').addEventListener('click',toggleAuto);$('#ot-reset').addEventListener('click',hardReset);$$('.incident-btn').forEach(b=>b.addEventListener('click',()=>inject(b.dataset.incident)));
window.addEventListener('resize',()=>requestAnimationFrame(drawEdges));
generator=setInterval(()=>{if(running)spawnJob()},900);chaosTimer=setInterval(()=>{if(running&&autoChaos){const types=['worker','rate','duplicate','corrupt','ack','partition','surge'];inject(types[Math.floor(Math.random()*types.length)],true)}},5200);tickTimer=setInterval(metrics,250);historyTimer=setInterval(sampleHistory,1000);drawEdges();hardReset();
})();