(()=>{
const q=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const input=q('#request-input'),run=q('#place-request'),fileInput=q('#surface-file'),fileSlip=q('#file-slip'),results=q('#result-papers'),understand=q('#paper-understand'),check=q('#paper-check'),route=q('#paper-route'),continueLine=q('#continue-line');
if(!input||!run||!results)return;
const examples={image:'ECの商品画像を10枚。正方形、白背景、来週金曜まで。文字入れなし。',automation:'毎朝届くCSVを整理して、重複を除いてGoogle Driveにまとめたい。失敗した時は二重実行しないようにしたい。',web:'スマホだけレイアウトが崩れるページを直したい。公開前にPCとモバイル両方確認したい。'};
function classify(t){if(/自動|CSV|スプレッド|API|Agent|workflow|ワークフロー/i.test(t))return'automation';if(/Web|サイト|ページ|HTML|CSS|レスポンシブ|スマホ/i.test(t))return'web';if(/動画|画像|生成|サムネ|商品画像|リール|SNS/i.test(t))return'creative';if(/PDF|Excel|データ|表|変換|整理/i.test(t))return'data';return'general'}
function analyze(t){const kind=classify(t);const count=(t.match(/\d+\s*(?:枚|本|件|個|ページ|点|文字|分|時間)/)||[])[0]||'未指定';const deadline=(t.match(/[^。\n]*(?:今日|明日|今週|来週|月曜|火曜|水曜|木曜|金曜|土曜|日曜|\d+月\d+日|まで)[^。\n]*/)||[])[0]||'未指定';const format=['正方形','縦','横','PDF','CSV','MP4','Excel','PNG','JPG'].filter(x=>t.toLowerCase().includes(x.toLowerCase()));const labels={creative:'画像・動画制作',automation:'自動化',web:'Web修正・制作',data:'データ整理',general:'内容確認'};const flow={creative:['条件整理','素材確認','制作','目視確認','差分修正','納品確認'],automation:['現状確認','副作用を分ける','試運転','実装','失敗テスト','記録'],web:['症状再現','戻せる状態を作る','局所修正','PC確認','モバイル確認','公開確認'],data:['入力確認','列と型を確認','変換','重複・欠損確認','件数照合','書き出し'],general:['目的確認','必要素材確認','作業範囲を決める','実行','確認','納品']}[kind];const missing=[];if(count==='未指定')missing.push('量・件数');if(deadline==='未指定')missing.push('期限');if(!format.length)missing.push('納品形式');if(!/素材|ファイル|画像|動画|データ|URL|リンク/.test(t))missing.push('元になる素材の有無');return{label:labels[kind],count,deadline,format:format.join(' / ')||'未指定',missing,flow}}
function render(t){const a=analyze(t);understand.innerHTML=`<small>01 / 読み取ったこと</small><h4>${esc(a.label)}</h4><ul><li>量：${esc(a.count)}</li><li>期限：${esc(a.deadline)}</li><li>形式：${esc(a.format)}</li></ul>`;check.innerHTML=`<small>02 / 先に確認</small><h4>${a.missing.length?'まだ決めたいこと':'条件はかなり揃っています'}</h4>${a.missing.length?`<ul>${a.missing.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<ul><li>素材と完成条件を最終確認すれば進められそうです。</li></ul>'}`;route.innerHTML=`<small>03 / 進め方</small><h4>最初から確認まで。</h4><code>${a.flow.map(esc).join(' → ')}</code>`;results.classList.add('open');continueLine.classList.add('show');setTimeout(()=>results.scrollIntoView({behavior:'smooth',block:'nearest'}),80)}
run.addEventListener('click',()=>{const t=input.value.trim();if(!t){input.focus();return}render(t)});input.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();run.click()}});document.querySelectorAll('[data-example]').forEach(b=>b.addEventListener('click',()=>{input.value=examples[b.dataset.example]||'';render(input.value)}));
async function inspect(file){if(!file)return;const size=file.size<1024*1024?`${(file.size/1024).toFixed(1)} KB`:`${(file.size/1024/1024).toFixed(2)} MB`;let detail=`${file.type||'種類不明'} / ${size}`;if(file.type.startsWith('image/')){try{const url=URL.createObjectURL(file),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=rej;img.src=url});detail+=` / ${img.naturalWidth}×${img.naturalHeight}px`;URL.revokeObjectURL(url)}catch{}}fileSlip.hidden=false;fileSlip.innerHTML=`<strong>${esc(file.name)}</strong><p>${esc(detail)}</p>`;understand.innerHTML=`<small>01 / ファイル</small><h4>外形を確認しました。</h4><ul><li>${esc(file.name)}</li><li>${esc(detail)}</li></ul>`;check.innerHTML=`<small>02 / 納品前に</small><h4>用途との照合が必要。</h4><ul><li>指定の形式か</li><li>必要な寸法・長さか</li><li>最終ファイル名で問題ないか</li></ul>`;route.innerHTML=`<small>03 / 次</small><h4>渡す前の順番。</h4><code>用途確認 → 形式確認 → 内容確認 → 名前を整える → 納品</code>`;results.classList.add('open');continueLine.classList.add('show')}
if(fileInput)fileInput.addEventListener('change',()=>inspect(fileInput.files[0]));const sheet=q('.input-sheet');if(sheet){['dragenter','dragover'].forEach(ev=>sheet.addEventListener(ev,e=>{e.preventDefault();sheet.classList.add('drag')}));['dragleave','drop'].forEach(ev=>sheet.addEventListener(ev,e=>{e.preventDefault();sheet.classList.remove('drag')}));sheet.addEventListener('drop',e=>inspect(e.dataTransfer.files[0]))}
})();